export type LayoutPageProps = {
  navItems: string;
  gallery?: string;
  galleryImages?: string;
  posts?: string;
  newsletter?: string;
  post?: string;
  galleries?: string;
  categories?: string;
  categoryName?: string;
  category?: string;
  page?: string;
  fbFeed?: string;
  fbEvents?: string;
  fbToken?: string;
  aboutInfo?: string;
  phrase?: string;
  locales?: string;
  locale?: string;
  defaultLocale?: string;
  headerGallery?:string;
  headerImage: string;
};
